name: Windows build for Zed

on:
  push:
    tags:
      - "daily-release-[0-9]+"
  workflow_dispatch:    # Add this line

env:
  CARGO_TERM_COLOR: always

jobs:
  zed:
    runs-on: windows-latest

    steps:
      - name: Enable long path support
        run: |
          git config --global core.longpaths true
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
        shell: powershell
    
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build Zed
        run: cargo build --release

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./target/release/zed.exe
          tag: ${{ github.ref_name }}
          overwrite: true
